<!DOCTYPE html>
<html>
<head>
    <title>Weekly Expense Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .total {
            font-weight: bold;
            text-align: right;
            margin-top: 20px;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 14px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">{{ $company->name }}</div>
        <h1>Weekly Expense Report</h1>
        <p>{{ now()->subDays(7)->format('M d, Y') }} - {{ now()->format('M d, Y') }}</p>
    </div>
    
    @if($expenses->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Date</th>
                    @if($expenses->first()->user)
                    <th>User</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($expenses as $expense)
                <tr>
                    <td>{{ $expense->description }}</td>
                    <td>${{ number_format($expense->amount, 2) }}</td>
                    <td>{{ $expense->created_at->format('M d, Y') }}</td>
                    @if($expense->user)
                    <td>{{ $expense->user->name }}</td>
                    @endif
                </tr>
                @endforeach
            </tbody>
        </table>
        
        <div class="total">
            Total: ${{ number_format($expenses->sum('amount'), 2) }}
        </div>
    @else
        <p>No expenses were recorded during this period.</p>
    @endif
    
    <div class="footer">
        <p>This is an automated report generated by {{ config('app.name') }}.</p>
        <p>If you have any questions, please contact your system administrator.</p>
    </div>
</body>
</html>