<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Weekly Expense Report</title>
    <style>
        /* Base styles */
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
        }

        /* Container styles */
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #ffffff;
        }

        /* Header styles */
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }

        /* Section styles */
        .section {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #ffffff;
            border: 1px solid #e9ecef;
            border-radius: 5px;
        }

        /* Table styles */
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .table th, .table td {
            padding: 12px;
            border: 1px solid #dee2e6;
            text-align: left;
        }
        .table th {
            background-color: #f8f9fa;
            font-weight: 600;
        }

        /* Highlight styles */
        .highlight {
            color: #dc3545;
            font-weight: 600;
        }
        .positive {
            color: #28a745;
            font-weight: 600;
        }

        /* Footer styles */
        .footer {
            margin-top: 30px;
            padding: 15px;
            text-align: center;
            font-size: 0.9em;
            color: #6c757d;
            border-top: 1px solid #e9ecef;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Weekly Expense Report</h1>
            <p>For the period: {{ $reportData['period']['start'] ?? 'N/A' }} to {{ $reportData['period']['end'] ?? 'N/A' }}</p>
        </div>

        <div class="section">
            <h2>Summary</h2>
            <table class="table">
                <tr>
                    <th>Total Expenses</th>
                    <td>${{ number_format($reportData['total_expenses'] ?? 0, 2) }}</td>
                </tr>
                <tr>
                    <th>Average Expense</th>
                    <td>${{ number_format($reportData['average_expense'] ?? 0, 2) }}</td>
                </tr>
                <tr>
                    <th>Week-over-Week Change</th>
                    <td class="{{ isset($reportData['week_over_week_change']) && $reportData['week_over_week_change'] >= 0 ? 'positive' : 'highlight' }}">
                        {{ isset($reportData['week_over_week_change']) ? number_format($reportData['week_over_week_change'], 2) . '%' : 'N/A' }}
                    </td>
                </tr>
            </table>
        </div>

        <div class="section">
            <h2>Expenses by Category</h2>
            <table class="table">
                <tr>
                    <th>Category</th>
                    <th>Total Amount</th>
                    <th>Number of Expenses</th>
                </tr>
                @forelse($reportData['expenses_by_category'] ?? [] as $category)
                <tr>
                    <td>{{ $category->category ?? 'Uncategorized' }}</td>
                    <td>${{ number_format($category->total_amount ?? 0, 2) }}</td>
                    <td>{{ $category->count ?? 0 }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="3" style="text-align: center;">No expenses recorded for this period</td>
                </tr>
                @endforelse
            </table>
        </div>

        <div class="section">
            <h2>Top Spenders</h2>
            <table class="table">
                <tr>
                    <th>Employee</th>
                    <th>Total Spent</th>
                </tr>
                @forelse($reportData['top_spenders'] ?? [] as $spender)
                <tr>
                    <td>{{ $spender->user->name ?? 'Unknown User' }}</td>
                    <td>${{ number_format($spender->total_amount ?? 0, 2) }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="2" style="text-align: center;">No spending data available</td>
                </tr>
                @endforelse
            </table>
        </div>

        <div class="footer">
            <p>This is an automated report generated by IbidapoExpense. Please contact your system administrator if you have any questions.</p>
            <p>Report generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
        </div>
    </div>
</body>
</html>
